SELECT TOP (1000) [GrainIdHash]
      ,[GrainIdN0]
      ,[GrainIdN1]
      ,[GrainTypeHash]
      ,[GrainTypeString]
      ,[GrainIdExtensionString]
      ,[ServiceId]
      ,[PayloadBinary]
	  ,CAST([PayloadBinary] AS VARCHAR(MAX)) AS PayloadJson
      ,[ModifiedOn]
      ,[Version]
  FROM [UrlShortener].[dbo].[OrleansStorage]
